env:
  browser: true
  es6: true
  node: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console: 0
  no-inline-comments: 0
  eqeqeq: 2
  react-hooks/rules-of-hooks:
    - error
  react-hooks/exhaustive-hooks:
    - warn
